### ISSUE TITLE
A bug need to fix!

### ISSUE THREAD

**Issue by lthero-big** [umd-huang-lab/WAVES#2]
Thanks for your work!!! We found a bug here: 

Before we run 'python cli.py' , we need to **add the following code to the bottom of cli.py**,otherwise it won't work

```
if __name__ == "__main__":
    cli()
```

**Comment by johnding1996** [comment]
Thanks for raising this issue. Yes, during our development, we actually install through `pip install -e .` and call the command-line interface through `wmbench [commands] [args]`. Thanks for letting us know. We will address the docs and code accordingly.
