### ISSUE TITLE
klvae16 model/config file missing.

### ISSUE THREAD

**Issue by Jazzhsu** [umd-huang-lab/WAVES#7]
kl-vae-16 model and config files are not present in the repo. Could you post the link of the model or upload the model to repo? Thank you.

**Comment by rabbanitw** [comment]
As the model is too large to host in this model, we ask that users download this model themselves. Please see https://github.com/CompVis/latent-diffusion (>Model Zoo >> Pretrained Autoencoding Models) for instructions on how to grab the kl-vae-16 model.
